# Generated by Django 4.1.4 on 2022-12-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
