# Generated by Django 4.1.4 on 2023-01-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Adress',
            new_name='adress',
        ),
    ]
